spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1ciVDOYezquEYQb
    url: jdbc:mariadb://101.34.76.31:3306/tools-dev
  data:
    redis:
      host: 101.34.76.31
      password: 1Bsw6BL2xNloQMh