spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/tools
  data:
    redis:
      host: 101.34.76.31
      password: 1Bsw6BL2xNloQMh